---
docker_users: []

dockge_port: 5001
dockge_dir: /home/will/dockge
dockge_stacks_path: /home/will/docker
docker_managed_dirs:
  - path: /home/will/docker
    link: ""
  - path: /home/will/dockge
    link: ""

docker_daemon_options:
  log-driver: json-file
  log-opts:
    max-size: "100m"
    max-file: "3"
  storage-driver: overlay2

docker_service_enabled: true
docker_service_state: started
