---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    managed:
      children:
        local:
        remote:

    local:
      hosts:
        sudostorage:
          ansible_host: sudostorage.sudoservers.com

    remote:
      hosts:
        brazil:
          ansible_host: brazil.tail1d0df.ts.net
