---
- name: Download Tailscale GPG key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"
    force: false
  tags: [tailscale]

- name: Add Tailscale apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
    filename: tailscale
  tags: [tailscale]

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true
  tags: [tailscale]

- name: Ensure tailscaled service is enabled and running
  ansible.builtin.service:
    name: tailscaled
    enabled: true
    state: started
  tags: [tailscale]
