---
- name: Local Servers
  hosts: local
  become: true

  roles:
    - role: base
      tags: [base]
    - role: ufw
      tags: [ufw]
    - role: users
      tags: [users]
    - role: docker
      tags: [docker]
    - role: tailscale
      tags: [tailscale]
    - role: growing-guide
      tags: [growing-guide]
    - role: family-sudoservers
      tags: [family-sudoservers]

- name: Remote Servers
  hosts: remote
  become: true

  roles:
    - role: base
      tags: [base]
    - role: ufw
      tags: [ufw]
    - role: users
      tags: [users]
    - role: docker
      tags: [docker]
    - role: oicoruja
      tags: [oicoruja]
